language: go

sudo: required

go:
  - 1.10.x

env:
  global:
    - NAME=managed-service-broker

stages:
  - test
  - compile
  - name: push
    if: fork = false

jobs:
  include:
    - stage: compile
      script:
        - make build_image TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
    - stage: push
      script:
        - docker login --password "$QUAY_PASSWORD" --username "$QUAY_USERNAME" quay.io
        - make build_image push TAG=$(git rev-parse --short ${TRAVIS_COMMIT})