language: go

sudo: required

go:
  - 1.10.x

env:
  global:
    - NAME=managed-service-broker

stages:
  - test
  - compile
  - name: push
    if: fork = false

jobs:
  include:
    - stage: compile
      script:
        - make build_image TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
    - stage: push
      script:
        - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
        - export TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
        - docker login --password "$QUAY_PASSWORD" --username "$QUAY_USERNAME" quay.io
        - make build_image push TAG=$TAG
        - docker tag quay.io/integreatly/$NAME:$TAG quay.io/integreatly/$NAME:$BRANCH
        - docker push quay.io/integreatly/$NAME:$BRANCH